// <auto-generated />
using Assignment2.BottomLayerPersistenceLogic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment2.Migrations
{
    [DbContext(typeof(StudentHelperContext))]
    [Migration("20200325110926_primaryKeysOnStudentAndTeacher")]
    partial class primaryKeysOnStudentAndTeacher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Assignment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Course", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AssignmentID")
                        .HasColumnType("bigint");

                    b.Property<long>("LectureID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Exercise", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LectureID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("LectureID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Lecture", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Student", b =>
                {
                    b.Property<string>("AUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CurrentSemester")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AUID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentAssignment", b =>
                {
                    b.Property<long>("StudentAUID")
                        .HasColumnType("bigint");

                    b.Property<long>("AssignmentID")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentAUID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentAUID", "AssignmentID");

                    b.HasIndex("AssignmentID");

                    b.HasIndex("StudentAUID1");

                    b.ToTable("StudentAssignment");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentCourse", b =>
                {
                    b.Property<string>("StudentAUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.HasKey("StudentAUID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentExercise", b =>
                {
                    b.Property<long>("StudentAUID")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseID")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentAUID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentAUID", "ExerciseID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("StudentAUID1");

                    b.ToTable("StudentExercise");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Teacher", b =>
                {
                    b.Property<string>("AUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("AssignmentID")
                        .HasColumnType("bigint");

                    b.Property<long>("AuidOfStudentBeingAssisted")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentAUID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AUID");

                    b.HasIndex("AssignmentID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("StudentAUID");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.TeacherCourse", b =>
                {
                    b.Property<string>("TeacherAUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherAUID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("TeacherCourse");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Assignment", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Exercise", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Lecture", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentAssignment", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Assignment", "Assignment")
                        .WithMany("StudentAssignment")
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Student", "Student")
                        .WithMany("StudentAssignment")
                        .HasForeignKey("StudentAUID1");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentCourse", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Course", "Course")
                        .WithMany("StudentsAttending")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentAUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.StudentExercise", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Exercise", "Exercise")
                        .WithMany("StudentExercise")
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Student", "Student")
                        .WithMany("StudentExercise")
                        .HasForeignKey("StudentAUID1");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.Teacher", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentAUID");
                });

            modelBuilder.Entity("Assignment2.TopLayer.Domain.TeacherCourse", b =>
                {
                    b.HasOne("Assignment2.TopLayer.Domain.Course", "Course")
                        .WithMany("TeachersResponsible")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.TopLayer.Domain.Teacher", "Teacher")
                        .WithMany("ResponsibleForTheseCourses")
                        .HasForeignKey("TeacherAUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
